# Generated by Django 4.0.6 on 2022-07-29 12:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=list, max_length=80)),
                ('usermoviename', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=100), blank=True, size=None)),
                ('usermovieimage', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=100), blank=True, size=None)),
                ('usermovieid', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), blank=True, size=None)),
            ],
        ),
    ]
