# Generated by Django 4.0.6 on 2022-07-30 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='usermovietype',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=100), default=['none'], size=None),
            preserve_default=False,
        ),
    ]
